import fs from 'node:fs';
const path='src/main.jsx';
let source=fs.readFileSync(path,'utf8');
source=source.replaceAll('??','||');
source=source.replace('<label>النوع *<select required value={f.case_type}onChange={e=>setF({...f,case_type:e.target.value})}><option value="">اختر</option><option value="aid">مساعدات</option><option value="orphan_sponsorship">كفالة أيتام</option></select></label>','<label>النوع *<select required value={f.case_type}onChange={e=>setF({...f,case_type:e.target.value})}><option value="">اختر</option><option value="aid">مساعدات</option><option value="orphan_sponsorship">كفالة أيتام</option></select></label><label>حالة البداية *<select required value={f.status}onChange={e=>setF({...f,status:e.target.value})}><option value="active">الحالات النشطة — تصرف شهريًا</option><option value="waiting">قائمة الانتظار</option></select></label>');
source=source.replace('<button className="primary save">إضافة إلى قائمة الانتظار</button>','<button className="primary save">{f.status===\'active\'?\'إضافة إلى الحالات النشطة\':\'إضافة إلى قائمة الانتظار\'}</button>');
source=source.replace("{page==='cases'&&<Cases cases={cases}amounts={amounts}select={setSelected}/>} ","{page==='cases'&&<Cases cases={cases}amounts={amounts}select={setSelected}refresh={loadCases}/>} ");
const casesStart=source.indexOf('function Cases('), waitingStart=source.indexOf('function Waiting('), childrenStart=source.indexOf('function Children(');
if(casesStart>=0&&waitingStart>casesStart&&childrenStart>waitingStart){
 const fn=`function Cases({cases,amounts,select,refresh}){const[q,setQ]=useState('');const list=cases.filter(c=>c.status==='active'&&(c.mother_name+' '+(c.phone||'')+' '+(c.address||'')).toLowerCase().includes(q.toLowerCase()));async function archive(e,c){e.stopPropagation();if(!confirm('هل تريد نقل هذه الحالة إلى أرشيف الحالات؟'))return;const{error}=await supabase.from('cases').update({status:'archived',updated_at:new Date().toISOString()}).eq('id',c.id);if(error){alert(error.message);return}await audit('archive','case',c.id,{from:'active',to:'archived'});refresh()}return <section className="panel"><div className="panel-head"><div><h2>الحالات النشطة</h2><p>الحالات التي تصرف شهريًا حاليًا.</p></div><span>{list.length} حالة</span></div><input className="search-input"placeholder="بحث باسم الأم أو الهاتف أو العنوان..."value={q}onChange={e=>setQ(e.target.value)}/><div className="case-list">{list.map(c=><div className="case-row"key={c.id}><button className="case-card"onClick={()=>select(c)}><b>{c.mother_name}</b><span>{c.address||'—'} · {c.case_type==='aid'?'مساعدات':'كفالة أيتام'} · {money(caseAmount(c,amounts))}</span>{c.notes&&<em>⚠️</em>}</button><button className="danger-action"onClick={e=>archive(e,c)}>حذف وأرشفة</button></div>)}</div></section>}
`;
 source=source.slice(0,casesStart)+fn+source.slice(waitingStart);
}
const ws=source.indexOf('function Waiting('), cs=source.indexOf('function Children(');
if(ws>=0&&cs>ws){
 const fn=`function Waiting({cases,amounts,select,refresh}){const list=[...cases.filter(c=>c.status==='waiting')].sort((a,b)=>(b.priority_override||b.children?.length||0)-(a.priority_override||a.children?.length||0));async function activate(e,c){e.stopPropagation();const{error}=await supabase.from('cases').update({status:'active',updated_at:new Date().toISOString()}).eq('id',c.id);if(error){alert(error.message);return}await audit('activate','case',c.id,{from:'waiting',to:'active'});refresh()}async function archive(e,c){e.stopPropagation();if(!confirm('هل تريد نقل هذه الحالة إلى الأرشيف؟'))return;const{error}=await supabase.from('cases').update({status:'archived',updated_at:new Date().toISOString()}).eq('id',c.id);if(error){alert(error.message);return}await audit('archive','case',c.id,{from:'waiting',to:'archived'});refresh()}return <section className="panel"><div className="panel-head"><div><h2>قائمة الانتظار</h2><p>الأولوية: 5+ ← 4 ← 3 ← 2 ← 1 ← بدون أطفال.</p></div><span>{list.length} حالة</span></div><div className="waiting-list">{list.map((c,i)=><div className="waiting-item"key={c.id}><button className="waiting-card"onClick={()=>select(c)}><b>#{i+1} · {c.mother_name}</b><span>{c.address||'—'} · {priorityLabel(priority(c))} · {money(caseAmount(c,amounts))}</span>{c.notes&&<em>⚠️</em>}</button><button className="primary waiting-action"onClick={e=>activate(e,c)}>إدخال للحالات النشطة</button><button className="danger-action waiting-delete"onClick={e=>archive(e,c)}>حذف وأرشفة</button></div>)}</div></section>}
`;
 source=source.slice(0,ws)+fn+source.slice(cs);
}
const ds=source.indexOf('function Dashboard('), after=source.indexOf('function Cases(');
if(ds>=0&&after>ds){
 const fn=`function Dashboard({cases,amounts,select,go}){const visible=cases.filter(c=>c.status!=='archived'),active=visible.filter(c=>c.status==='active'),waiting=visible.filter(c=>c.status==='waiting'),allKids=visible.flatMap(c=>c.children||[]),review=allKids.filter(c=>c.gender==='male'&&age(c.birth_date)>=18),total=active.reduce((n,c)=>n+caseAmount(c,amounts),0);return <><section className="welcome"><div><p>مرحبًا بك 👋</p><h2>لوحة التحكم</h2><span>ملخص سريع لأهم بيانات النظام.</span></div><button className="primary"onClick={()=>go('add')}>+ إضافة حالة</button></section><section className="stats"><article className="stat"><span>إجمالي الأسر</span><strong>{visible.length}</strong></article><article className="stat"><span>الحالات النشطة</span><strong>{active.length}</strong></article><article className="stat"><span>قائمة الانتظار</span><strong>{waiting.length}</strong></article><article className="stat"><span>الأطفال المسجلون</span><strong>{allKids.length}</strong></article></section><section className="stats dashboard-secondary"><article className="stat"><span>أطفال يحتاجون مراجعة 18 سنة</span><strong>{review.length}</strong></article><article className="stat"><span>الأطفال المؤهلون حاليًا</span><strong>{allKids.filter(eligible).length}</strong></article><article className="stat"><span>إجمالي الالتزام الشهري</span><strong>{money(total)}</strong></article><article className="stat"><span>حالات تحتاج مراجعة</span><strong>{review.length}</strong></article></section><section className="panel"><div className="panel-head"><div><h3>الحالات الأخيرة</h3><p>اضغط على أي أسرة لعرض البطاقة الكاملة.</p></div></div><div className="case-list">{visible.slice(0,8).map(c=><button className="case-card"key={c.id}onClick={()=>select(c)}><b>{c.mother_name}</b><span>{c.status==='active'?'نشطة':'في الانتظار'} · {c.case_type==='aid'?'مساعدات':'كفالة أيتام'} · {money(caseAmount(c,amounts))}</span>{c.notes&&<em>⚠️</em>}</button>)}</div></section></>}
`;
 source=source.slice(0,ds)+fn+source.slice(after);
}
const navNeedle="const nav=[['dashboard','لوحة التحكم','⌂'],['cases','الحالات النشطة','◉'],['add','إضافة حالة','+'],['waiting','قائمة الانتظار','≡'],['children','الأطفال','♙'],['reports','التقارير','▤'],['external','التوزيع الخارجي','◇']];";
const navReplacement="const nav=[['dashboard','لوحة التحكم','⌂'],['cases','الحالات النشطة','◉'],['add','إضافة حالة','+'],['waiting','قائمة الانتظار','≡'],['children','الأطفال','♙'],['reports','التقارير','▤'],['external','التوزيع الخارجي','◇'],['archive','أرشيف الحالات','▤']];";
if(source.includes(navNeedle)&&!source.includes("['archive','أرشيف الحالات','▤']"))source=source.replace(navNeedle,navReplacement);
const renderNeedle="{page==='external'&&<ExternalDistribution cases={cases}/>} {page==='amounts'&&isAdmin&&<Amounts amounts={amounts}refresh={loadAmounts}/>}";
const renderReplacement="{page==='external'&&<ExternalDistribution cases={cases}/>} {page==='archive'&&<Archive cases={cases}amounts={amounts}refresh={loadCases}/>} {page==='amounts'&&isAdmin&&<Amounts amounts={amounts}refresh={loadAmounts}/>}";
if(source.includes(renderNeedle)&&!source.includes("page==='archive'"))source=source.replace(renderNeedle,renderReplacement);
if(!source.includes('function Archive({cases,amounts,refresh})')){
 const marker='function Dashboard({cases,amounts,select,go})';
 const archive=`function Archive({cases,amounts,refresh}){const list=cases.filter(c=>c.status==='archived').sort((a,b)=>new Date(b.deleted_at||0)-new Date(a.deleted_at||0));async function restore(e,c){e.stopPropagation();if(!confirm('استعادة هذه الحالة إلى الحالات النشطة؟'))return;const{error}=await supabase.from('cases').update({status:'active',updated_at:new Date().toISOString()}).eq('id',c.id);if(error){alert(error.message);return}await audit('restore','case',c.id,{from:'archived',to:'active'});refresh()}return <section className="panel"><div className="panel-head"><div><h2>أرشيف الحالات</h2><p>كل الحالات المؤرشفة مع بيانات الإضافة والحذف.</p></div><span>{list.length} حالة</span></div><div className="archive-list">{list.length===0?<div className="empty">لا توجد حالات في الأرشيف.</div>:list.map(c=><div className="archive-item"key={c.id}><div className="archive-card"><div className="archive-title"><b>{c.mother_name}</b><span className="archive-status">مؤرشفة</span></div><span>{c.address||'—'} · {c.case_type==='aid'?'مساعدات':'كفالة أيتام'} · {money(caseAmount(c,amounts))}</span><span>أضيفت بواسطة: {c.created_by||'مسجل في السجل'}</span><span>حُذفت بواسطة: {c.deleted_by||'مسجل في السجل'}</span><span>تاريخ الحذف: {c.deleted_at?new Date(c.deleted_at).toLocaleString('ar-EG'):'غير مسجل'}</span></div><button className="restore-action"onClick={e=>restore(e,c)}>استعادة للحالات النشطة</button></div>)}</div></section>}`;
 if(source.includes(marker))source=source.replace(marker,archive+'\n'+marker);
}
fs.writeFileSync(path,source);
