import fs from 'node:fs';
const file='src/main.jsx';
const cssFile='src/styles.css';
let source=fs.readFileSync(file,'utf8');
const navNeedle="const nav=[['dashboard','لوحة التحكم','⌂'],['cases','الحالات النشطة','◉'],['add','إضافة حالة','+'],['waiting','قائمة الانتظار','≡'],['children','الأطفال','♙'],['reports','التقارير','▤'],['external','التوزيع الخارجي','◇']];";
const navReplacement="const nav=[['dashboard','لوحة التحكم','⌂'],['cases','الحالات النشطة','◉'],['add','إضافة حالة','+'],['waiting','قائمة الانتظار','≡'],['children','الأطفال','♙'],['reports','التقارير','▤'],['external','التوزيع الخارجي','◇'],['archive','أرشيف الحالات','▤']];";
if(source.includes(navNeedle)&&!source.includes("['archive','أرشيف الحالات','▤']"))source=source.replace(navNeedle,navReplacement);
const renderNeedle="{page==='external'&&<ExternalDistribution cases={cases}/>} {page==='amounts'&&isAdmin&&<Amounts amounts={amounts}refresh={loadAmounts}/>}";
const renderReplacement="{page==='external'&&<ExternalDistribution cases={cases}/>} {page==='archive'&&<Archive cases={cases}amounts={amounts}refresh={loadCases}/>} {page==='amounts'&&isAdmin&&<Amounts amounts={amounts}refresh={loadAmounts}/>}";
if(source.includes(renderNeedle)&&!source.includes("page==='archive'"))source=source.replace(renderNeedle,renderReplacement);
if(!source.includes('function Archive({cases,amounts,refresh})')){
 const marker='function Dashboard({cases,amounts,select,go})';
 const archive=`function Archive({cases,amounts,refresh}){const list=cases.filter(c=>c.status==='archived').sort((a,b)=>new Date(b.deleted_at||0)-new Date(a.deleted_at||0));async function restore(e,c){e.stopPropagation();if(!confirm('استعادة هذه الحالة إلى الحالات النشطة؟'))return;const{error}=await supabase.from('cases').update({status:'active',deleted_at:null,deleted_by:null,updated_at:new Date().toISOString()}).eq('id',c.id);if(error){alert(error.message);return}await audit('restore','case',c.id,{from:'archived',to:'active'});refresh()}return <section className="panel"><div className="panel-head"><div><h2>أرشيف الحالات</h2><p>الحالات التي تم حذفها من القوائم الحالية مع الاحتفاظ بسجلها.</p></div><span>{list.length} حالة</span></div><div className="archive-list">{list.length===0?<div className="empty">لا توجد حالات في الأرشيف.</div>:list.map(c=><div className="archive-item"key={c.id}><div className="archive-card"><div className="archive-title"><b>{c.mother_name}</b><span className="archive-status">مؤرشفة</span></div><span>{c.address||'—'} · {c.case_type==='aid'?'مساعدات':'كفالة أيتام'} · {money(caseAmount(c,amounts))}</span><span>أضيفت بواسطة: {c.created_by||'غير مسجل'}</span><span>حُذفت بواسطة: {c.deleted_by||'غير مسجل'}</span><span>تاريخ الحذف: {c.deleted_at?new Date(c.deleted_at).toLocaleString('ar-EG'):'غير مسجل'}</span></div><button className="restore-action"onClick={e=>restore(e,c)}>استعادة للحالات النشطة</button></div>)}</div></section>}`;
 if(source.includes(marker))source=source.replace(marker,archive+'\n'+marker);
}
let css=fs.readFileSync(cssFile,'utf8');
if(!css.includes('.archive-list{')){css+=`\n.archive-list{display:grid;gap:12px;margin-top:16px}.archive-item{display:flex;gap:12px;align-items:stretch}.archive-card{flex:1;min-width:0;border:1px solid #e6ebe9;background:#fff;border-radius:14px;padding:15px;text-align:right;color:#30271b;display:grid;gap:7px}.archive-title{display:flex;align-items:center;justify-content:space-between;gap:10px}.archive-status{background:#d5d3c6;color:#30271b;border-radius:999px;padding:4px 9px;font-size:11px;font-weight:800}.archive-card>span{font-size:12px;color:#817765}.restore-action{border:1px solid #30271b;background:#d5d3c6;color:#30271b;border-radius:11px;padding:10px 16px;font-weight:800;min-width:175px;align-self:stretch}.restore-action:hover{background:#30271b;color:#d5d3c6}@media(max-width:760px){.archive-item{flex-direction:column}.restore-action{width:100%;min-height:46px}}`;fs.writeFileSync(cssFile,css)}
fs.writeFileSync(file,source);
console.log('archive navigation restored safely');
